CREATE TABLE IF NOT EXISTS PHERF.IMMUTABLE_ENTITY_DATA (
    CUSTOMER_ID CHAR(15) NOT NULL,
    PARTITION_KEY CHAR(3) NOT NULL,
    CREATED_DATE DATE,
    CREATED_BY CHAR(15),
    LAST_UPDATE DATE,
    LAST_UPDATE_BY CHAR(15),
    SYSTEM_MODSTAMP DATE
    CONSTRAINT PK PRIMARY KEY (
        CUSTOMER_ID,
        PARTITION_KEY
    )
) VERSIONS=1, IMMUTABLE_ROWS=true, MULTI_TENANT=true, COLUMN_ENCODED_BYTES=0

